
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 114
#define YY_END_OF_BUFFER 115
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[472] =
    {   0,
        0,    0,    0,    0,    0,    0,  115,  113,  103,  103,
       91,  113,  113,   97,   90,  113,   85,   86,   95,   94,
       82,   93,   89,  113,   50,   51,   83,   79,   98,   84,
       99,  102,  104,  104,   87,  113,   88,  100,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,   80,  101,   81,   92,    3,    3,
        3,  111,  112,  103,    0,   78,    0,   56,    0,    0,
        0,    0,    0,    0,    0,   64,   81,   73,   65,    0,
       96,    0,   62,   70,   60,   71,   61,   72,    0,   53,
        1,    0,   63,   53,   50,    0,    0,   50,   50,    0,

       50,   51,   51,   51,   51,   88,   80,   87,   69,   75,
       77,   76,   68,  104,    0,    0,    0,    0,   66,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,   12,  104,  104,  104,  104,  104,
      104,   20,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,   67,   74,    3,    3,    2,  111,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       55,    0,    0,    0,    0,   57,    0,   53,    0,    4,
        0,   54,   50,   50,   50,   50,   52,   51,   51,   51,
       51,   59,   58,    0,    0,    0,    0,  104,  104,  104,

      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,   18,  104,
      104,   22,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,    0,    0,
        0,    0,    0,    0,    0,    0,  105,    0,    0,    0,
        0,    0,    0,    0,   53,   54,   50,   52,   52,   52,
       51,    0,    0,    0,    0,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,    5,  104,    7,    8,  104,
      104,  104,  104,   14,   15,  104,  104,   19,  104,   23,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,

      104,  104,   36,  104,  104,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   52,   52,
       52,   52,    0,    0,    0,    0,  104,  104,   42,  104,
      104,  104,  104,  104,  104,  104,    6,    9,  104,  104,
      104,  104,   17,  104,  104,  104,  104,   27,  104,  104,
      104,  104,  104,  104,   34,  104,  104,   38,    0,    0,
        0,    0,  106,    0,    0,    0,  109,    0,    0,   52,
        0,    0,    0,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,   13,   16,   21,  104,  104,
       26,   28,   29,   30,   31,   32,  104,  104,  104,    0,

        0,    0,    0,  107,    0,    0,    0,    0,    0,  104,
      104,   41,  104,  104,  104,  104,  104,  104,  104,  104,
       11,  104,  104,   33,  104,  104,    0,    0,  108,    0,
        0,    0,    0,   39,   40,   43,   44,  104,  104,  104,
      104,   49,   10,   24,   25,   35,   37,    0,    0,  110,
        0,    0,    0,  104,   46,  104,  104,    0,    0,    0,
       45,  104,  104,  104,  104,  104,  104,  104,   48,   47,
        0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   36,   36,   38,   36,   39,   36,   36,
       36,   36,   40,   41,   42,   36,   36,   43,   36,   36,
       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   36,   58,   59,   60,   61,
       62,   63,   36,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[77] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        3,    1,    1,    4,    1,    1,    1,    1,    1,    5,
        5,    6,    1,    1,    1,    1,    7,    3,    6,    6,
        6,    6,    6,    6,    8,    8,    8,    8,    8,    8,
        8,    9,    9,    1,    9,    1,    1,    8,    5,    5,
        6,    6,    6,    5,    8,    8,    8,    8,    8,    8,
        9,    8,    8,    9,    8,    9,    9,    9,    8,    9,
        8,    8,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[534] =
    {   0,
        0,    0,   74,   75,   72,   73, 1084, 1085,   79,   88,
     1057,   78,   92,   75,   85,   75, 1085, 1085, 1056,   83,
     1085,   86,   86,   91,  134,  104, 1054, 1085,  105, 1054,
       89, 1085, 1034,  114, 1085,   76, 1085, 1052,  144,   74,
       84,   91,  116,  121,  141,   88,  145,  143,   82,  151,
       87,  149,  150,  153, 1085,  139, 1085, 1085, 1074, 1073,
     1056,    0, 1085,  219,  209, 1085,  157, 1085,  195,  223,
      224, 1021,  101,  178, 1016, 1085, 1085, 1085, 1085,  123,
     1085,  215, 1085, 1085, 1085, 1085, 1085, 1085, 1054,  234,
     1085, 1068, 1085,  269,  276,  226,  284,  203,  159,    0,

      219,  299,  233,  181,  266, 1085, 1085, 1085, 1044, 1085,
     1085, 1085, 1043, 1023,  207,  224,    0,    0, 1085,  265,
      188,  189,  207,  266,  250,  197,  208,  282,  247,  285,
      289,  295,  294,  297,  300,  303,  302,  304,  301,  308,
      305, 1022,  314,  315,  319,  316,  320,  332,  334,  337,
      338,  342,  341, 1085, 1085, 1063, 1062, 1085,    0, 1003,
      386,    0,    0,    0, 1009,  997, 1009, 1057, 1008,  997,
     1085,  391,    0,    0,    0, 1085,  393, 1085, 1054, 1085,
      368,  396,  352, 1085, 1018,  996,  382,  355, 1085, 1016,
      994, 1085, 1085,    0,    0,    0,    0,  364,  378,  380,

      383,  384,  388,  382,  390,  387,  359,  399,  403,  409,
      393,  402,  411,  312,  413,  414,  418,  420, 1007,  408,
      419, 1006,  427,  428,  430,  432,  433,  434,  435,  436,
      438,  441,  439,  442,  444,  446,  445,  455,  496,    0,
      535,    0,  993,  996,  991, 1044, 1085,  987,  992,  498,
        0,  579,    0,  490,  500, 1085, 1085,  485,  470,  473,
     1085,    0,    0,    0,    0,  480,  468,  485,  461,  486,
      481,  492,  504,  505,  501,  999,  185,  998,  997,  506,
      503,  508,  488,  996,  995,  518,  526,  994,  516,  993,
      528,  531,  533,  536,  538,  534,  549,  553,  569,  570,

      558,  562,  992,  560,  582,  609,    0,    0,    0,  975,
     1032,  980,  966, 1029,  607,    0,    0,    0,  579, 1085,
      993,  971,    0,    0,    0,    0,  578,  580,  984,  589,
      591,  593,  595,  596,  598,  600,  983,  982,  597,  604,
      611,  599,  981,  612,  614,  617,  621,  980,  623,  622,
      626,  624,  228,  625,  979,  627,  628,  978,    0,    0,
      969, 1018, 1085, 1017,  967, 1015, 1085,    0,    0, 1085,
        0,    0,    0,  972,  634,  636,  639,  641,  644,  646,
      648,  649,  652,  650,  657,  822,  821,  820,  658,  659,
      818,  814,  813,  812,  810,  805,  661,  663,  662,    0,

      702,  842,  835, 1085,  779,    0,  701,    0,    0,  669,
      673,  747,  674,  675,  679,  677,  684,  685,  690,  686,
      746,  691,  692,  745,  697,  695,    0,  785, 1085,  749,
        0,    0,    0,  742,  737,  736,  735,  698,  700,  708,
      705,  680,  529,  448,  360,  311,  271,    0,  758, 1085,
        0,    0,    0,  707,  270,  714,  722,    0,    0,    0,
      125,  721,  724,  723,  728,  725,  726,  727,   94,   93,
     1085,  793,  802,  811,  820,  825,  834,  843,  851,  859,
      868,  873,  875,  877,  879,  881,  883,  889,  894,  896,
      898,  900,  902,  904,  906,  908,  910,  912,  914,  916,

      918,  920,  922,  924,  926,  932,  941,  946,  948,  950,
      952,  954,  956,  958,  960,  966,  971,  973,  975,  977,
      979,  981,  987,  992,  994,  996,  998, 1000, 1002, 1004,
     1006, 1008, 1010
    } ;

static yyconst flex_int16_t yy_def[534] =
    {   0,
      471,    1,  472,  472,  473,  473,  471,  471,  471,  471,
      471,  474,  471,  471,  471,  475,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  476,  476,  471,  471,  471,  471,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  471,  471,  471,  471,  477,  477,
      471,  478,  471,  471,  471,  471,  474,  471,  479,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  475,
      471,  480,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  481,  471,  471,  471,  471,  471,  471,  471,  482,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  476,  471,  474,  483,  484,  471,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  471,  471,  477,  477,  471,  478,  471,
      474,  485,  486,  487,  471,  471,  471,  488,  471,  471,
      471,  475,  489,  490,  491,  471,  471,  471,  481,  471,
      471,  471,  471,  471,  471,  471,  482,  471,  471,  471,
      471,  471,  471,  492,  493,  494,  495,  476,  476,  476,

      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  474,  496,
      474,  497,  471,  471,  471,  488,  471,  471,  471,  475,
      498,  475,  499,  471,  471,  471,  471,  471,  471,  471,
      471,  500,  501,  502,  503,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476,  476,  476,  476,  474,  504,  241,  505,  471,
      506,  471,  471,  507,  475,  508,  252,  509,  471,  471,
      471,  471,  510,  511,  512,  513,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  514,  515,
      471,  506,  471,  516,  471,  507,  471,  517,  518,  471,
      519,  520,  521,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  522,

      474,  523,  516,  471,  471,  524,  475,  525,  526,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  527,  523,  471,  471,
      528,  529,  530,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  531,  471,  471,
      532,  533,  513,  476,  476,  476,  476,  515,  518,  520,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
        0,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471
    } ;

static yyconst flex_uint16_t yy_nxt[1162] =
    {   0,
        8,    9,   10,    9,    9,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   26,   27,   28,   29,   30,   31,   32,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   34,   33,   33,
       33,   33,   33,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   33,   47,   33,   48,   33,
       33,   33,   33,   49,   50,   51,   52,   53,   54,   33,
       33,   33,   55,   56,   57,   58,   60,   60,   63,   63,
       64,   64,   64,   64,   68,   81,   65,   61,   61,   64,
       64,   64,   64,   70,   78,   65,   71,   84,   63,   63,

       76,   77,   86,   89,   91,   90,   90,   90,   85,   92,
       79,   87,   88,  107,  112,  113,   93,  117,  115,   82,
      116,   94,   69,  102,  102,  102,  115,  108,  115,  109,
      110,  115,  115,  171,  145,  115,   97,  115,  115,  131,
      129,  103,  118,   72,   73,  104,  132,  130,   74,  141,
       75,   94,  133,   95,   95,   96,   97,  150,  115,  166,
      115,  167,  105,   68,  154,  115,   97,   82,  134,  115,
      104,   98,  120,  121,  122,   99,  100,  135,  123,  136,
      124,  137,  125,  126,  127,  115,   97,  115,  115,  115,
      138,  128,  101,  115,  115,  115,  185,  115,  142,  139,

       99,   69,  140,  100,  144,  143,  146,  147,  153,  151,
       70,  152,  155,   70,  161,  161,  148,  186,  190,  149,
       64,   64,   64,   64,   70,   70,   65,   70,   71,  115,
       68,  168,  115,  115,  172,  172,  162,  163,  169,  191,
      183,  115,  337,   94,  184,   96,   96,   96,  194,  200,
      201,  115,  115,   90,   90,   90,  173,  174,   97,  202,
      184,  164,  205,  206,  163,  160,  177,  178,   69,  184,
      188,  178,  115,  195,  189,   72,   73,  183,   97,  160,
       74,  175,   75,  396,  174,  184,  177,  178,   90,   90,
       90,  115,  178,   94,  115,   95,   95,   96,  181,  189,

      181,  177,  178,  182,  182,  182,  178,  189,   97,  115,
      115,  204,  208,   98,  115,  115,   94,   99,  102,  102,
      102,  177,  178,  198,  188,  203,  115,  178,   97,  115,
      199,   97,  189,  115,  101,  207,  103,  209,  115,  115,
      104,  115,   99,  211,  115,  115,  115,  115,  115,  115,
      213,   97,  115,  210,  212,  115,  115,  105,  115,  115,
      115,  283,  218,  115,  115,  104,  214,  215,  216,  217,
      220,  219,  221,  224,  228,  223,  115,  227,  115,  222,
      230,  115,  115,  225,  226,  115,  115,  182,  182,  182,
      232,  229,   68,  184,  234,  231,  189,  238,  236,  233,

      237,  171,  235,  115,  115,  239,  239,  254,  115,  254,
      250,  250,  255,  255,  255,  182,  182,  182,  184,  258,
      266,  189,  115,  259,  115,  275,  115,  115,  115,  256,
       69,  115,  115,  256,  115,   82,  271,  115,  273,  267,
      260,  268,  269,  115,  270,  272,  115,  115,  259,  256,
      274,  277,  115,  115,  256,  115,  279,  115,  115,  282,
      276,  278,  115,  115,  115,  284,  280,  281,  287,  288,
      286,  115,  115,  285,  115,  289,  115,  115,  115,  115,
      115,  290,  115,  115,  291,  115,  115,  296,  115,  115,
      115,  300,  115,  304,  295,  292,  294,  303,  293,  115,

      302,  297,   68,  301,  298,  115,  299,  321,  171,  255,
      255,  255,  115,  305,  320,  306,  306,  315,  315,  255,
      255,  255,  319,  330,  115,  115,  320,  328,  322,  115,
      115,  319,  115,  178,  327,  332,  115,  178,  331,  320,
       69,   68,   82,  329,  333,  115,  341,  115,  115,  115,
      115,  320,  115,  178,  308,  308,  308,  335,  178,  339,
      115,  336,  115,  308,  308,  308,  308,  308,  308,  334,
      115,  338,  115,  115,  340,  115,  344,  115,  115,   69,
      115,  342,  115,  308,  308,  308,  308,  308,  308,  171,
      349,  343,  345,  115,  346,  350,  347,  115,  317,  317,

      317,  348,  115,  352,  115,  351,  115,  317,  317,  317,
      317,  317,  317,  115,  115,   68,  356,  171,  355,  353,
      320,  354,  115,   82,  115,  357,  115,  317,  317,  317,
      317,  317,  317,  115,  358,  115,  376,  115,  375,  115,
      115,  115,  115,  115,  115,  320,  382,  377,  115,  379,
      383,   82,  381,   69,  378,  115,  115,  384,  115,  387,
      380,  115,  385,  386,  388,  115,  115,  115,  115,  115,
      115,  115,  115,  390,  392,  393,  394,  397,  115,  389,
      115,  391,  410,  115,  399,  115,  412,  398,  115,  395,
      115,  413,  115,  115,  115,  411,  115,  414,  417,  419,

      418,  115,  115,  115,  415,  115,  115,  115,   68,  423,
      422,  171,  416,  115,  424,  425,  420,  115,  115,  115,
      426,  115,  421,  115,  115,  437,  435,  438,  115,  115,
      115,  440,  441,  434,  115,  115,  115,  442,  443,  115,
      439,  115,  115,  436,  115,   82,   69,  447,  446,  115,
      449,  115,  115,  449,  444,  450,  456,  445,  115,  449,
      455,  454,  449,  457,  450,  115,  115,  115,  115,  115,
      115,  115,  115,  450,  465,  466,  467,  461,  462,  115,
      115,  115,  450,  463,  469,  464,  115,  429,  468,  115,
      115,  115,  470,   59,   59,   59,   59,   59,   59,   59,

       59,   59,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       80,   80,   80,   80,   80,   80,   80,   80,   80,  114,
      114,  430,  114,  114,  156,  156,  156,  404,  156,  156,
      156,  156,  156,  159,  429,  159,  159,  159,  159,  115,
      159,  159,   67,   67,  115,   67,  115,  115,  115,   67,
       80,   80,  115,   80,  115,  115,  115,   80,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  187,  187,  196,
      196,  197,  197,  240,  240,  241,  241,  242,  242,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  251,  251,

      252,  252,  253,  253,  262,  262,  263,  263,  264,  264,
      265,  265,  307,  307,  309,  309,  316,  316,  318,  318,
      323,  323,  324,  324,  325,  325,  326,  326,  359,  359,
      360,  360,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      368,  368,  369,  369,  371,  371,  372,  372,  373,  373,
      374,  374,  400,  400,  401,  401,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  406,  406,  407,  407,  408,
      408,  114,  114,  409,  409,  427,  427,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  431,  431,  432,  432,

      433,  433,  448,  448,  451,  451,  452,  452,  453,  453,
      458,  458,  459,  459,  460,  460,  115,  367,  405,  404,
      363,  402,  115,  115,  115,  115,  115,  115,  115,  370,
      370,  367,  365,  364,  363,  361,  115,  115,  115,  115,
      115,  115,  115,  115,  314,  313,  247,  312,  311,  310,
      115,  115,  261,  261,  257,  257,  180,  249,  248,  247,
      245,  244,  243,  169,  157,  157,  115,  115,  193,  192,
      180,  176,  170,  165,  158,  157,  157,  119,  115,  111,
      106,   83,   66,  471,    7,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471
    } ;

static yyconst flex_int16_t yy_chk[1162] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    5,    6,
        9,    9,    9,    9,   12,   16,    9,    3,    4,   10,
       10,   10,   10,   13,   15,   10,   13,   20,    5,    6,

       14,   14,   22,   23,   24,   23,   23,   23,   20,   24,
       15,   22,   22,   29,   31,   31,   24,   36,   40,   16,
       34,   26,   12,   26,   26,   26,   49,   29,   41,   29,
       29,   51,   46,   80,   49,   42,   26,  470,  469,   42,
       40,   26,   36,   13,   13,   26,   42,   41,   13,   46,
       13,   25,   42,   25,   25,   25,   26,   51,   34,   73,
       43,   73,   26,   67,   56,   44,   25,   80,   43,  461,
       26,   25,   39,   39,   39,   25,   25,   43,   39,   44,
       39,   44,   39,   39,   39,   45,   25,   48,   39,   47,
       44,   39,   25,   52,   53,   50,   99,   54,   47,   45,

       25,   67,   45,   25,   48,   47,   50,   50,   54,   52,
       65,   53,   56,   65,   69,   69,   50,   99,  104,   50,
       64,   64,   64,   64,   70,   71,   64,   70,   71,  277,
      116,   74,  121,  122,   82,   82,   69,   69,   74,  104,
       98,  126,  277,   96,   98,   96,   96,   96,  115,  121,
      122,  123,  127,   90,   90,   90,   82,   82,   96,  123,
      101,   69,  126,  127,   69,   65,   90,   90,  116,   98,
      103,   90,  353,  115,  103,   71,   71,  101,   96,   70,
       71,   82,   71,  353,   82,  101,   90,   90,   94,   94,
       94,  129,   90,   95,  125,   95,   95,   95,   97,  103,

       97,   94,   94,   97,   97,   97,   94,  105,   95,  120,
      124,  125,  129,   95,  455,  447,  102,   95,  102,  102,
      102,   94,   94,  120,  105,  124,  128,   94,   95,  130,
      120,  102,  105,  131,   95,  128,  102,  130,  133,  132,
      102,  134,   95,  132,  135,  139,  137,  136,  138,  141,
      134,  102,  140,  131,  133,  446,  214,  102,  143,  144,
      146,  214,  139,  145,  147,  102,  135,  136,  137,  138,
      141,  140,  143,  145,  147,  144,  148,  146,  149,  143,
      148,  150,  151,  145,  145,  153,  152,  181,  181,  181,
      149,  147,  161,  183,  151,  148,  188,  153,  152,  150,

      152,  172,  151,  207,  445,  161,  161,  177,  198,  177,
      172,  172,  177,  177,  177,  182,  182,  182,  183,  187,
      198,  188,  199,  187,  200,  207,  204,  201,  202,  182,
      161,  206,  203,  182,  205,  172,  203,  211,  205,  199,
      187,  200,  201,  208,  202,  204,  212,  209,  187,  182,
      206,  209,  220,  210,  182,  213,  211,  215,  216,  213,
      208,  210,  217,  221,  218,  215,  212,  212,  218,  220,
      217,  223,  224,  216,  225,  221,  226,  227,  228,  229,
      230,  223,  231,  233,  224,  232,  234,  229,  235,  237,
      236,  233,  444,  237,  228,  225,  227,  236,  226,  238,

      235,  230,  239,  234,  231,  269,  232,  259,  250,  254,
      254,  254,  267,  238,  260,  239,  239,  250,  250,  255,
      255,  255,  258,  269,  266,  271,  258,  267,  259,  268,
      270,  260,  283,  255,  266,  271,  272,  255,  270,  260,
      239,  241,  250,  268,  272,  275,  283,  281,  273,  274,
      280,  258,  282,  255,  241,  241,  241,  274,  255,  281,
      289,  275,  286,  241,  241,  241,  241,  241,  241,  273,
      287,  280,  291,  443,  282,  292,  289,  293,  296,  241,
      294,  286,  295,  241,  241,  241,  241,  241,  241,  252,
      295,  287,  291,  297,  292,  296,  293,  298,  252,  252,

      252,  294,  301,  298,  304,  297,  302,  252,  252,  252,
      252,  252,  252,  299,  300,  306,  302,  315,  301,  299,
      319,  300,  327,  252,  328,  304,  305,  252,  252,  252,
      252,  252,  252,  330,  305,  331,  328,  332,  327,  333,
      334,  339,  335,  342,  336,  319,  335,  330,  340,  332,
      336,  315,  334,  306,  331,  341,  344,  339,  345,  342,
      333,  346,  340,  341,  344,  347,  350,  349,  352,  354,
      351,  356,  357,  346,  349,  350,  351,  354,  375,  345,
      376,  347,  375,  377,  357,  378,  376,  356,  379,  352,
      380,  377,  381,  382,  384,  375,  383,  378,  381,  383,

      382,  385,  389,  390,  379,  397,  399,  398,  401,  390,
      389,  407,  380,  410,  397,  398,  384,  411,  413,  414,
      399,  416,  385,  415,  442,  414,  411,  415,  417,  418,
      420,  417,  418,  410,  419,  422,  423,  419,  420,  426,
      416,  425,  438,  413,  439,  407,  401,  426,  425,  441,
      430,  454,  440,  430,  422,  430,  440,  423,  456,  449,
      439,  438,  449,  441,  449,  462,  457,  464,  463,  466,
      467,  468,  465,  430,  463,  464,  465,  454,  456,  437,
      436,  435,  449,  457,  467,  462,  434,  428,  466,  424,
      421,  412,  468,  472,  472,  472,  472,  472,  472,  472,

      472,  472,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  474,  474,  474,  474,  474,  474,  474,  474,  474,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  476,
      476,  405,  476,  476,  477,  477,  477,  403,  477,  477,
      477,  477,  477,  478,  402,  478,  478,  478,  478,  396,
      478,  478,  479,  479,  395,  479,  394,  393,  392,  479,
      480,  480,  391,  480,  388,  387,  386,  480,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  482,  482,  483,
      483,  484,  484,  485,  485,  486,  486,  487,  487,  488,
      488,  488,  488,  488,  488,  488,  488,  488,  489,  489,

      490,  490,  491,  491,  492,  492,  493,  493,  494,  494,
      495,  495,  496,  496,  497,  497,  498,  498,  499,  499,
      500,  500,  501,  501,  502,  502,  503,  503,  504,  504,
      505,  505,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      508,  508,  509,  509,  510,  510,  511,  511,  512,  512,
      513,  513,  514,  514,  515,  515,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  517,  517,  518,  518,  519,
      519,  520,  520,  521,  521,  522,  522,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  524,  524,  525,  525,

      526,  526,  527,  527,  528,  528,  529,  529,  530,  530,
      531,  531,  532,  532,  533,  533,  374,  366,  365,  364,
      362,  361,  358,  355,  348,  343,  338,  337,  329,  322,
      321,  314,  313,  312,  311,  310,  303,  290,  288,  285,
      284,  279,  278,  276,  249,  248,  246,  245,  244,  243,
      222,  219,  191,  190,  186,  185,  179,  170,  169,  168,
      167,  166,  165,  160,  157,  156,  142,  114,  113,  109,
       92,   89,   75,   72,   61,   60,   59,   38,   33,   30,
       27,   19,   11,    7,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[115] =
    {   0,
0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "CCode.l"


/*Universal char name*/
/*float exponente*/
/*int length*/
/*whitespace*/
#line 20 "CCode.l"
	#include "CCode.tab.h"
	#include <string.h>
	#include <stdio.h>
	#include <stdlib.h>
	
	#define YYDECL int yylex()	

	extern void yyerror(const char *);
#line 940 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define IFILE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 31 "CCode.l"


#line 1163 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 472 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1085 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 33 "CCode.l"
{BEGIN(COMMENT);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 34 "CCode.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 35 "CCode.l"
{}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 36 "CCode.l"
{ yyerror("Comentario sin terminar\n"); }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 37 "CCode.l"
{}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "CCode.l"
{ return AUTO; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "CCode.l"
{ return BREAK; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "CCode.l"
{ return CASE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 43 "CCode.l"
{ return CHAR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "CCode.l"
{ return CONST; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "CCode.l"
{ return CONTINUE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "CCode.l"
{ return DEFAULT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "CCode.l"
{ return DO; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "CCode.l"
{ return DOUBLE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "CCode.l"
{ return ELSE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "CCode.l"
{ return ENUM; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "CCode.l"
{ return EXTERN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "CCode.l"
{ return FLOAT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "CCode.l"
{ return FOR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "CCode.l"
{ return GOTO; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "CCode.l"
{ return IF; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "CCode.l"
{ return INLINE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "CCode.l"
{ return INT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 58 "CCode.l"
{ return LONG; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "CCode.l"
{ return REGISTER; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 60 "CCode.l"
{ return RESTRICT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 61 "CCode.l"
{ return RETURN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 62 "CCode.l"
{ return SHORT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 63 "CCode.l"
{ return SIGNED; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 64 "CCode.l"
{ return SIZEOF; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 65 "CCode.l"
{ return STATIC; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 66 "CCode.l"
{ return STRUCT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 67 "CCode.l"
{ return SWITCH; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 68 "CCode.l"
{ return TYPEDEF; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 69 "CCode.l"
{ return UNION; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 70 "CCode.l"
{ return UNSIGNED; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 71 "CCode.l"
{ return VOID; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 72 "CCode.l"
{ return VOLATILE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 73 "CCode.l"
{ return WHILE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "CCode.l"
{ return ALIGNAS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "CCode.l"
{ return ALIGNOF; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "CCode.l"
{ return ATOMIC; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "CCode.l"
{ return BOOL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "CCode.l"
{ return COMPLEX; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "CCode.l"
{ return GENERIC; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "CCode.l"
{ return IMAGINARY; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "CCode.l"
{ return NORETURN; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "CCode.l"
{ return STATIC_ASSERT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 84 "CCode.l"
{ return THREAD_LOCAL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 85 "CCode.l"
{ return FUNC_NAME; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "CCode.l"
{ yylval.intval = (int)strtol(yytext,NULL,8); return I_CONSTANT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 89 "CCode.l"
{ yylval.intval = atoi(yytext); return I_CONSTANT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 91 "CCode.l"
{yylval.intval = (int)strtol(yytext,NULL,0); return I_CONSTANT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 94 "CCode.l"
{yylval.floatval = atof(yytext); return F_CONSTANT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 95 "CCode.l"
{ yylval.floatval = atof(yytext); return F_CONSTANT; }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 98 "CCode.l"
{ yylval.strval = strdup(yytext); return STRING_LITERAL; }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 100 "CCode.l"
{ yylval.strval = strdup(yytext); return STRING_LITERAL; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 102 "CCode.l"
{ return ELLIPSIS; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 103 "CCode.l"
{ return RIGHT_ASSIGN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 104 "CCode.l"
{ return LEFT_ASSIGN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 105 "CCode.l"
{ return ADD_ASSIGN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 106 "CCode.l"
{ return SUB_ASSIGN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 107 "CCode.l"
{ return MUL_ASSIGN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 108 "CCode.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 109 "CCode.l"
{ return MOD_ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 110 "CCode.l"
{ return AND_ASSIGN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 111 "CCode.l"
{ return XOR_ASSIGN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 112 "CCode.l"
{ return OR_ASSIGN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 113 "CCode.l"
{ return RIGHT_OP; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 114 "CCode.l"
{ return LEFT_OP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 115 "CCode.l"
{ return INC_OP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "CCode.l"
{ return DEC_OP; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 117 "CCode.l"
{ return PTR_OP; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 118 "CCode.l"
{ return AND_OP; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 119 "CCode.l"
{ return OR_OP; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 120 "CCode.l"
{ return LE_OP; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 121 "CCode.l"
{ return GE_OP; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 122 "CCode.l"
{ return EQ_OP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 123 "CCode.l"
{ return NE_OP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 124 "CCode.l"
{ return ';'; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 125 "CCode.l"
{ return '{'; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 126 "CCode.l"
{ return '}'; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 127 "CCode.l"
{ return ','; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 128 "CCode.l"
{ return ':'; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 129 "CCode.l"
{ return '='; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 130 "CCode.l"
{ return '('; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 131 "CCode.l"
{ return ')'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 132 "CCode.l"
{ return '['; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 133 "CCode.l"
{ return ']'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 134 "CCode.l"
{ return '.'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 135 "CCode.l"
{ return '&'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 136 "CCode.l"
{ return '!'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 137 "CCode.l"
{ return '~'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 138 "CCode.l"
{ return '-'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 139 "CCode.l"
{ return '+'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 140 "CCode.l"
{ return '*'; }
	YY_BREAK
case 96:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 141 "CCode.l"
{ return '/'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 142 "CCode.l"
{ return '%'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 143 "CCode.l"
{ return '<'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 144 "CCode.l"
{ return '>'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 145 "CCode.l"
{ return '^'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 146 "CCode.l"
{ return '|'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 147 "CCode.l"
{ return '?'; }
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 148 "CCode.l"
{/* ignoramos los espacios */}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 151 "CCode.l"
{yylval.strval = strdup(yytext); return IDENTIFIER;}
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 154 "CCode.l"
{/*no haremos nada con el preprocesador*/}
	YY_BREAK
case 106:
/* rule 106 can match eol */
YY_RULE_SETUP
#line 155 "CCode.l"
{/*no haremos nada con el preprocesador*/}
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 156 "CCode.l"
{/*no haremos nada con el preprocesador*/}
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 157 "CCode.l"
{/*no haremos nada con el preprocesador*/}
	YY_BREAK
case 109:
/* rule 109 can match eol */
YY_RULE_SETUP
#line 158 "CCode.l"
{/*no haremos nada con el preprocesador*/}
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 160 "CCode.l"
{ BEGIN IFILE; }
	YY_BREAK
case 111:
/* rule 111 can match eol */
YY_RULE_SETUP
#line 162 "CCode.l"
{
			{ int c;
			  int indice = 0;
			  char filename[1024] = {0};
		
			  while((c = input()) && c != '\n');
			   }
				
			//printf("Archivo include es: %s\n",yytext);
			BEGIN INITIAL;
			}
	YY_BREAK
case 112:
/* rule 112 can match eol */
YY_RULE_SETUP
#line 174 "CCode.l"
{printf("Error en include\n");
			BEGIN INITIAL;
		}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 178 "CCode.l"
{ } //printf("syntax error, found:'%c'\n",*yytext); 
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 180 "CCode.l"
ECHO;
	YY_BREAK
#line 1832 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IFILE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 472 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 472 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 471);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 180 "CCode.l"






